name: Update delpoy branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Update
              run: git subtree push --prefix dist origin gh-pages
